/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.MIniProjeto;

import java.awt.event.KeyEvent;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno.saolucas
 */
public class frGerenciadoDeTarefas extends javax.swing.JFrame {

    /**
     * Creates new form frGerenciadoDeTarefas
     */
    public frGerenciadoDeTarefas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTarefa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaListaDeTarefas = new javax.swing.JTextArea();
        btnSalvarTarefa = new javax.swing.JButton();
        btnExcluirTarefa = new javax.swing.JButton();
        btnListarTarefas = new javax.swing.JButton();
        btnEditarTarefa = new javax.swing.JButton();
        btnListaVazia = new javax.swing.JButton();
        btnQuantidadeTarefas = new javax.swing.JButton();
        btnOrdemAlfabetica = new javax.swing.JButton();
        btnLimparTudo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gerenciador de Tarefas ");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Digite a tarefa :");

        txtTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarefaActionPerformed(evt);
            }
        });
        txtTarefa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTarefaKeyPressed(evt);
            }
        });

        txtaListaDeTarefas.setColumns(20);
        txtaListaDeTarefas.setRows(5);
        jScrollPane1.setViewportView(txtaListaDeTarefas);

        btnSalvarTarefa.setText("Salvar Tarefa");
        btnSalvarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarTarefaActionPerformed(evt);
            }
        });
        btnSalvarTarefa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalvarTarefaKeyPressed(evt);
            }
        });

        btnExcluirTarefa.setText("Excluir Tarefa");
        btnExcluirTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTarefaActionPerformed(evt);
            }
        });

        btnListarTarefas.setText("Listar Tarefas");
        btnListarTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarTarefasActionPerformed(evt);
            }
        });

        btnEditarTarefa.setText("Editar Tarefa");
        btnEditarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTarefaActionPerformed(evt);
            }
        });

        btnListaVazia.setText("Verificar Lista vazia");
        btnListaVazia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaVaziaActionPerformed(evt);
            }
        });

        btnQuantidadeTarefas.setText("Quantidade de Tarefas");
        btnQuantidadeTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantidadeTarefasActionPerformed(evt);
            }
        });

        btnOrdemAlfabetica.setText("Ordenar de A-Z");
        btnOrdemAlfabetica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdemAlfabeticaActionPerformed(evt);
            }
        });

        btnLimparTudo.setText("Limpar Lista ");
        btnLimparTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparTudoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtTarefa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvarTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluirTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListaVazia, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuantidadeTarefas)
                    .addComponent(btnOrdemAlfabetica, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(181, 181, 181))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarTarefa)
                    .addComponent(btnExcluirTarefa)
                    .addComponent(btnListarTarefas))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEditarTarefa)
                        .addGap(18, 18, 18)
                        .addComponent(btnListaVazia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnQuantidadeTarefas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOrdemAlfabetica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimparTudo))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Gerenciador gerenciar = new Gerenciador();
    Scanner ler = new Scanner(System.in);
    private void txtTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarefaActionPerformed

    private void btnSalvarTarefaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvarTarefaKeyPressed


    }//GEN-LAST:event_btnSalvarTarefaKeyPressed

    private void txtTarefaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTarefaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSalvarTarefa.doClick();
        }
    }//GEN-LAST:event_txtTarefaKeyPressed

    private void btnSalvarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarTarefaActionPerformed
        gerenciar.adicionarTarefa(txtTarefa.getText());
        txtTarefa.setText(null);
        txtTarefa.requestFocus();
    }//GEN-LAST:event_btnSalvarTarefaActionPerformed

    private void btnExcluirTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTarefaActionPerformed
        btnListarTarefas.doClick();
        int numeroDaLista = Integer.parseInt(JOptionPane.showInputDialog(null, "Informe o número da tarefa que deseja excluir :"));
        if (JOptionPane.showConfirmDialog(null, "Tem certeza que quer excluir essa tarefa ? ", "confirme", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            gerenciar.excluirTarefa((numeroDaLista - 1));
            btnListarTarefas.doClick();
        } else {
            JOptionPane.showMessageDialog(null, "Exclusão cancelada ");
        }
    }//GEN-LAST:event_btnExcluirTarefaActionPerformed

    private void btnListarTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarTarefasActionPerformed
        txtaListaDeTarefas.setText(gerenciar.listarTarefas()); 
    }//GEN-LAST:event_btnListarTarefasActionPerformed

    private void btnEditarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTarefaActionPerformed
        btnListarTarefas.doClick();
        int cod = Integer.parseInt(JOptionPane.showInputDialog(null, "Informe o número da tarefa que deseja alterar :"))-1;
        if (cod > gerenciar.retornarTamanho() || cod < 0) {
            JOptionPane.showMessageDialog(null, "A tarefa não existe");
        } else {
            String novaTarefa = JOptionPane.showInputDialog(null, "Informe a nova tarefa :");
            gerenciar.alterar(cod, novaTarefa);
            btnListarTarefas.doClick();
        }
    }//GEN-LAST:event_btnEditarTarefaActionPerformed

    private void btnListaVaziaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaVaziaActionPerformed
        gerenciar.verificarListaVazia();
    }//GEN-LAST:event_btnListaVaziaActionPerformed

    private void btnQuantidadeTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantidadeTarefasActionPerformed
        gerenciar.quantidadeDeTarefas();
    }//GEN-LAST:event_btnQuantidadeTarefasActionPerformed

    private void btnOrdemAlfabeticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdemAlfabeticaActionPerformed
        gerenciar.colocarListaEmOrdemAlfabetica();
    }//GEN-LAST:event_btnOrdemAlfabeticaActionPerformed

    private void btnLimparTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparTudoActionPerformed
        gerenciar.excluirTodaLista();
        
    }//GEN-LAST:event_btnLimparTudoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frGerenciadoDeTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frGerenciadoDeTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frGerenciadoDeTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frGerenciadoDeTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frGerenciadoDeTarefas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarTarefa;
    private javax.swing.JButton btnExcluirTarefa;
    private javax.swing.JButton btnLimparTudo;
    private javax.swing.JButton btnListaVazia;
    private javax.swing.JButton btnListarTarefas;
    private javax.swing.JButton btnOrdemAlfabetica;
    private javax.swing.JButton btnQuantidadeTarefas;
    private javax.swing.JButton btnSalvarTarefa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtTarefa;
    private javax.swing.JTextArea txtaListaDeTarefas;
    // End of variables declaration//GEN-END:variables
}
